modLoader = "kotlinforforge"
loaderVersion = "[5,)"
license = "MIT"

[[mods]]
modId = "cobblemon_incubator"
version = "${version}"
displayName = "Cobblemon Incubator"
authors = "RapidMesck"
description = '''
A Cobblemon and Cobbreeding addon that adds a customizable Egg Incubator with faster hatching, advanced filters, PC delivery, and Pasture automation.
'''

[[dependencies.cobblemon_incubator]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_incubator]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_incubator]]
modId = "cobblemon"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemon_incubator]]
modId = "cobbreeding"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemon_incubator]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
